# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 东北出马实录
subtitle: 胡四太奶
description: 不忘初心、方得始终

#头像里面的标题
avatarTitle: 东北出马实录
avatarDesc: 不忘初心、方得始终

author: JordanCZ

# 语言
language: zh-Hans



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.hstn2469.cn/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tsyouasd
github_username:  tsyouasd

encoding: utf-8

# Build settings
markdown: kramdown
theme: minima
 


baidu-analysis: 3feafcfe9dc92d24d9ff078707570959

# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 关于博主

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 文化传播, description: tags, url: '/tags'}
    - {title: 作者简介, description: about, url: '/about'}       


# Pagination 分页
plugins: [jekyll-paginate,jekyll-feed,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"
 


          
